name: ë¬¸ì„œ ë°°í¬

on:
  # "main" ë¸Œëœì¹˜ì— í‘¸ì‹œí•  ë•Œ ë§ˆë‹¤ ì›Œí¬í”Œë¡œìš° ì‘ë™
  push:
    branches: [ "main" ]

# GitHub Pages ì— ë°°í¬í•˜ê¸° ìœ„í•œ GITHUB_TOKEN ê¶Œí•œ ì„¤ì •
permissions:
  contents: read
  pages: write
  id-token: write
# ë™ì‹œì„± ë°°í¬ í—ˆìš©
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      # GitHub Pages ë¡œ ë°°í¬í•˜ê¸° ìœ„í•œ í•„ìˆ˜ ì„¤ì •
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13  #ìµœì‹ ë²„ì „
    steps:
    - name: ì²´í¬ì•„ì›ƒ ğŸ›ï¸
      uses: actions/checkout@v3
    - name: DocC ë¬¸ì„œ ë¹Œë“œ
      run: |
        xcodebuild docbuild -scheme PackageDocCExample \
          -derivedDataPath /tmp/docbuild \
          -destination 'generic/platform=iOS';
        $(xcrun --find docc) process-archive \
          transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/PackageDocCExample.doccarchive \
          --hosting-base-path package-docc-example \
          --output-path docs;
        echo "<script>window.location.href += \"/documentation/packagedoccexample\"</script>" > docs/index.html
    - name: artifact ì—…ë¡œë“œ
      uses: actions/upload-pages-artifact@v1
      with:
        # docs ê²½ë¡œì— ìˆëŠ” ê²ƒë§Œ ì—…ë¡œë“œ
        path: 'docs'
    - name: GitHub Pages ì— ë°°í¬
      id: deployment
      uses: actions/deploy-pages@v1



      
